// Generated by CoffeeScript 1.6.3
(function() {
  window.game.resources = [
    {
      name: "maptiles",
      type: "image",
      src: "data/img/map/maptiles.png"
    }, {
      name: "map01",
      type: "tmx",
      src: "data/map/map01.tmx"
    }
  ];

}).call(this);
